AllCops:
  TargetRubyVersion: 2.5

  DisplayCopNames: true
  DisplayStyleGuide: false

#
# Layout
#

# This is a remnant of old SUSE-style alignment for hashes, The table format
# looks more human readable.
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

#
# Metrics
#

# The default is just too small.
Metrics/AbcSize:
  Max: 30

# The default is just too small. A limit of 100 looks reasonable and many other
# projects (including inside of SUSE) are also using this value.
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

#
# Style
#

# This forces us to create a new object for no real reason.
Style/MultipleComparison:
  Enabled: false

# This is a common SUSE configuration value: the performance difference between
# single and double quotes is no longer there, and so it's better to be
# consistent and force only double quotes.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Same as Style/StringLiterals.
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
