# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base:             8bc8ccc710eafd73d43cd59ac8881aadc89f7a6ab55f1ac11c97fb436a3931cc78c38e735e664958d9e793725f3d52178f4e2c376c346edbaca3936aebf66e27
  encryption_private_key_path: <%= ENV["PORTUS_KEY_PATH"] || "examples/development/vagrant/conf/ca_bundle/server.key" %>
  portus_password:             "portus1234"

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:             <%= ENV["PORTUS_SECRET_KEY_BASE"] %>
  encryption_private_key_path: <%= ENV["PORTUS_KEY_PATH"] %>
  portus_password:             <%= ENV["PORTUS_PASSWORD"] %>
