#!/usr/bin/env bash

# Wait for mariadb
while true; do
    if bundle exec rake db:migrate:reset; then
        bundle exec rake db:seed
        break
    fi

    echo "Waiting for mariadb to be ready in 5 seconds"
    sleep 5
done

pumactl -F /srv/Portus/config/puma.rb start
