apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-storage
  labels:
    storage: mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data/mariadb
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-storage
  labels:
    storage: mariadb
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
