# NOTE: this file should be hidden somehow, or recreated only from the CLI. This
# has been done this way to illustrate better the example.

apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
type: Opaque
data:
  root: cG9ydHVz
  password: cG9ydHVz
